Resources:
  SampleDynamoTableChangeIt:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: ${self:custom.dynamodb.DeletionPolicy}
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: ${self:custom.dynamodb.SAMPLEDYNAMOTABLE_CHANGEIT_TABLE_PIT_RECOVERY}
      SSESpecification: ${self:custom.dynamodb.SAMPLEDYNAMOTABLE_CHANGEIT_TABLE_SSE_SPECIFICATION}
      TimeToLiveSpecification: ${self:custom.dynamodb.SAMPLEDYNAMOTABLE_CHANGEIT_TABLE_TTL_SPECIFICATION}
      Tags:
        - Key: service
          Value: ${self:custom.package.name}
        - Key: stage
          Value: ${self:provider.stage}
Outputs:
  SampleDynamoTableChangeIt:
    Description: DynamoDB table - SampleDynamoTableChangeIt, change the name as per your need.
    Value:
      Ref: SampleDynamoTableChangeIt
